name: MeshTalk
options:
  bundleIdPrefix: chat.meshtalk
  deploymentTarget:
    iOS: 16.0
    macOS: 13.0
  createIntermediateGroups: true

settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1

targets:
  MeshTalk_iOS:
    type: application
    platform: iOS
    sources:
    - MeshTalk
    resources:
    - MeshTalk/Assets.xcassets
    - MeshTalk/LaunchScreen.storyboard
    info:
      path: MeshTalk/Info.plist
      properties:
        CFBundleDisplayName: MeshTalk
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSBluetoothAlwaysUsageDescription: MeshTalk uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: MeshTalk uses Bluetooth to discover and connect with other MeshTalk users nearby.
        UIBackgroundModes:
        - bluetooth-central
        - bluetooth-peripheral
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
        - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
        - UIInterfaceOrientationPortrait
        - UIInterfaceOrientationPortraitUpsideDown
        - UIInterfaceOrientationLandscapeLeft
        - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CFBundleURLTypes:
        - CFBundleURLSchemes:
          - meshtalk
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.meshtalk
      PRODUCT_NAME: MeshTalk
      INFOPLIST_FILE: MeshTalk/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: MeshTalk/MeshTalk.entitlements
    dependencies:
    - target: MeshTalkShareExtension
      embed: true

  MeshTalk_macOS:
    type: application
    platform: macOS
    sources:
    - MeshTalk
    resources:
    - MeshTalk/Assets.xcassets
    info:
      path: MeshTalk/Info.plist
      properties:
        CFBundleDisplayName: MeshTalk
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSBluetoothAlwaysUsageDescription: MeshTalk uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: MeshTalk uses Bluetooth to discover and connect with other MeshTalk users nearby.
        CFBundleURLTypes:
        - CFBundleURLSchemes:
          - meshtalk
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.meshtalk
      PRODUCT_NAME: MeshTalk
      INFOPLIST_FILE: MeshTalk/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: MeshTalk/MeshTalk-macOS.entitlements

  MeshTalkShareExtension:
    type: app-extension
    platform: iOS
    sources:
    - MeshTalkShareExtension
    info:
      path: MeshTalkShareExtension/Info.plist
      properties:
        CFBundleDisplayName: MeshTalk
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.meshtalk.ShareExtension
      INFOPLIST_FILE: MeshTalkShareExtension/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      CODE_SIGN_ENTITLEMENTS: MeshTalkShareExtension/MeshTalkShareExtension.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES

  MeshTalkTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
    - MeshTalkTests
    dependencies:
    - target: MeshTalk_iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.meshtalk.tests
      INFOPLIST_FILE: MeshTalkTests/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/MeshTalk.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MeshTalk
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y

  MeshTalkTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
    - MeshTalkTests
    dependencies:
    - target: MeshTalk_macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.meshtalk.tests
      INFOPLIST_FILE: MeshTalkTests/Info.plist
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/MeshTalk.app/Contents/MacOS/MeshTalk
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y

schemes:
  MeshTalk (iOS):
    build:
      targets:
        MeshTalk_iOS: all
        MeshTalkShareExtension: all
    run:
      config: Debug
      executable: MeshTalk_iOS
    test:
      config: Debug
      targets:
      - MeshTalkTests_iOS
    profile:
      config: Release
      executable: MeshTalk_iOS
    analyze:
      config: Debug
    archive:
      config: Release

  MeshTalk (macOS):
    build:
      targets:
        MeshTalk_macOS: all
    run:
      config: Debug
      executable: MeshTalk_macOS
    test:
      config: Debug
      targets:
      - MeshTalkTests_macOS
    profile:
      config: Release
      executable: MeshTalk_macOS
    analyze:
      config: Debug
    archive:
      config: Release
